// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjwNFse-LuxZbi_cN6Fluym8duXCpOvw',
    appId: '1:1050226441344:web:02823c5d8247497eb3ba65',
    messagingSenderId: '1050226441344',
    projectId: 'cuidapet-6ece4',
    authDomain: 'cuidapet-6ece4.firebaseapp.com',
    storageBucket: 'cuidapet-6ece4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ipYj_VvlnKQfyaxZ1HfycCz5eQA74WA',
    appId: '1:1050226441344:android:7690f9b60261c2f5b3ba65',
    messagingSenderId: '1050226441344',
    projectId: 'cuidapet-6ece4',
    storageBucket: 'cuidapet-6ece4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb_2u2MPCZvWxUtC1hLg2PtqhhEJMMCO8',
    appId: '1:1050226441344:ios:808b3eee95658f10b3ba65',
    messagingSenderId: '1050226441344',
    projectId: 'cuidapet-6ece4',
    storageBucket: 'cuidapet-6ece4.appspot.com',
    iosClientId: '1050226441344-fr0phtlqmiiv0tigbckrhtjup4qc82l0.apps.googleusercontent.com',
    iosBundleId: 'com.offices.flutterCuidapet',
  );
}
